config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  #get "/articles", to: "articles#index"
  #get "/articles/:id", to: "articles#show"
  #resources :articles

  resources :articles, param: :url_field

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "about", to: "about#index"
  get "gothanimeangel", to: "about#gothanimeangel"
  get "peacesignmiku", to: "about#peacesignmiku"

  resources :about do
    collection do
      get :gothanimeangel
      get :peacesignmiku
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["title"]
    end
    
    def to_param
        url_field
    end

    def self.per_page
        3
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end

    def gothanimeangel
    end

    def peacesignmiku
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @q = Article.ransack(params[:q])
    @per_page = params[:per_page] || Article.per_page || 3
    #@articles = @q.result(distinct: true).page(params[:page]).order("uploadDate ASC").paginate(page: params[:page], :per_page => @per_page)
    @articles = @q.result(distinct: true).page(params[:page]).order("#{params[:sort_by]} #{params[:sort_order]}").paginate(page: params[:page], :per_page => @per_page)
  end

  def show
    #@article = Article.find(params[:id])
    @article = Article.find_by(url_field: params[:url_field])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/about/gothanimeangel.html.erb
<h2 class="page_title">About "Gothic Anime Angel"</h2>
<div id="about_goth">
    <img src="https://static.zerochan.net/Suzuhira.Hiro.full.766980.jpg" id="goth_anime_angel">
    <br></br>
    This illustration has become famous on the Internet for having been a top result in Google Images for search terms such as "goth anime girl" back in the 2000s, having been used on many websites, blogs, forums, and the like. The image itself has become individually well-known under the moniker "gothic anime angel". In this article, I would like to dive into the origins of this iconic artwork.
    <br></br>
    <b>Who drew "gothic anime angel"?</b>
    <br></br>
    In the current decade, it is fortunately not too difficult to identify the artist of this illustration thanks to image boards! The artist of "gothic anime angel" is none other than <b><a href="https://en.wikipedia.org/wiki/Hiro_Suzuhira">Hiro Suzuhira</a></b>, who is well known for being the character designer for the visual novels <a href="https://vndb.org/v28">Shuffle!</a> (2004) and <a href="https://vndb.org/v1194">Yosuga no Sora</a> (2008). She is currently working as a freelance illustrator, and is part of a doujin circle known as <a href="https://web.archive.org/web/20111006183518/http://heart-work.info/">"HEART WORK"</a>.
    <br></br>
    <b>Who is "gothic anime angel"?</b>
    <br></br>
    Although Hiro Suzuhira is famous for her work in the visual novel industry, the "gothic anime angel" illustration does <u><b>NOT</b></u> depict a character from a visual novel or a manga, but rather an <u><b>original character (OC)</b></u>. The character is often <u><b>incorrectly</b></u> identified as <a href="https://vndb.org/c57818">Yun</a> from the 2004 visual novel <a href="https://vndb.org/v1566">Monochrome</a> due to the fact that Suzuhira worked as a character designer and illustrator for the game and also the similarities between the character designs of "gothic anime angel" and Yun such as both characters being angels, dressing in a gothic style, and having long blonde hair.
    <br></br>
    To further evidence that "gothic anime angel" is an original character: Danbooru user <a href="https://danbooru.donmai.us/users/68250">henmere</a> states (<a href="https://danbooru.donmai.us/posts/540348#comment_2157333">here</a>) that according to page 116 of the Girls Girls Girls! E☆2 Illustration Collection artbook by Hiro Suzuhira, "gothic anime angel" was "drawn for E☆2's <b>original figure project (2005, E☆2 Vol.1.)."</b> E☆2 is a bimonthly Japanese magazine published by Mediation that features illustrations by various artists that depict original bishoujo characters (<a href="https://ja.wikipedia.org/wiki/E%E2%98%862">Source</a>).
    <br></br>
    <b>When was "gothic anime angel" made?</b>
    <br></br>
    As mentioned earlier, the "gothic anime angel" illustration was created for E☆2's 2005 original figure project.
    <br></br>
    An <a href="https://www.animenewsnetwork.com/interest/2020-01-03/western-fan-artists-draw-tribute-art-of-hiro-suzuhira-gothic-anime-angel/.155007">article on Anime News Network</a> about "gothic anime angel" claims that the image "has been around the web since at least 2004". Although I was personally unable to find an instance of this image online prior to 2006 (<a href="https://e-shuushuu.net/image/16627/">here</a>), I am very inclined to believe that the image has indeed been used online earlier than 2006 and that these older websites that used it are likely now defunct and therefore unable to be accessed in modern times.
    <br></br>
    A <a href="https://www.animenewsnetwork.com/bbs/phpBB2/viewtopic.php?t=3146718">forum post</a> on the discussion of the previously mentioned Anime News Network article stated that when asked, Hiro Suzuhira stated that she never uploaded the illustration online herself (until 2018!) and that the image originated from an artbook. At some point, the artbook was scanned by a fan and uploaded online, from where the image gained popularity.
    <br></br>
    The <a href="https://www.zerochan.net/766980">Zerochan</a><a href="https://www.zerochan.net/2443414">posts</a> for this illustration have tagged it as appearing in two of Hiro Suzuhira's artbooks: <a href="https://myfigurecollection.net/item/44243">Girls Girls Girls! - 1 (2007, in collaboration with Tony Taka)</a> and <a href="https://isbndb.com/book/9784048539999">Chronicle - Suzuhira Hiro Artworks (2008)</a>. 
    <br></br>
    The release dates of these artbooks don't support the idea that this illustration has existed since "at least 2004". However, it is possible that the image was present in Suzuhira's older artbooks, and that the titles of these artbooks may not have been tagged onto the Zerochan posts (which is fair, it's very unrealistic to expect someone to look through 20+ artbooks just for that).
    <br></br>
    <b>What was the origin of "gothic anime angel?</b>
    <br></br>
    In the previous section "Who is 'gothic anime angel'?", it was mentioned that the "gothic anime angel" illustration was made for E☆2's original figure project in 2005. Indeed, a <a href="https://myfigurecollection.net/item/26364">1/8 resin figurine garage kit</a> based on the artwork was released in 2005 at the Clayz Moero Matsuri 2005 exhibition as a collaboration between Hiro Suzuhira and sculptor <a href="https://myfigurecollection.net/entry/8199">Miyagawa Takeshi</a>.
    <br></br>
    <div id="gk_pics"><img src="https://static.myfigurecollection.net/upload/pictures/2021/07/18/2788305.jpeg" id="g_left"><img src="https://static.myfigurecollection.net/upload/pictures/2021/07/18/2788306.jpeg" id="g_right">
    </div>
    <b>Above:</b> Official promotional pictures of the 2005 garage kit figurine (courtesy of MyFigureCollection user <a href="https://myfigurecollection.net/profile/ichigosalad">ichigosalad</a>)
    <br></br>
    In 2006, a <a href="https://myfigurecollection.net/item/191159">pre-painted version</a> of the original garage kit figurine was released at the Clayz Moero Matsuri 2006 exhibition. Both the garage kit and pre-painted versions of the figurine were manufactured by <a href="https://web.archive.org/web/20081101150350/http://clayz-online.com/">Clayz</a>.
    <br></br>
    <img src="https://static.myfigurecollection.net/upload/pictures/2019/04/17/2195319.jpeg" id="p_left">
    <img src="https://static.myfigurecollection.net/upload/pictures/2019/08/20/2283366.jpeg" id="p_right">
    <br>
    <b>Above:</b> Pictures of the 2006 pre-painted figurine (courtesy of MyFigureCollection user <a href="https://myfigurecollection.net/profile/dead-wolfwood">dead-wolfwood</a>)
    <br></br>
    Through accessing an <a href="https://web.archive.org/web/20060103064343/http:/clayz-online.com/maturi/maturi_cata.html">archive snapshot from 2006 of Clayz's online store</a>, the listing for the figure can be seen, titled as "鈴平ひろ先生×宮川武　コラボ作品
    キャラ名未定" (Hiro Suzuhira x Takeshi Miyagawa Collaboration Work, Character Name Undecided), further confirming that "gothic anime angel" is not Yun from Monochrome, but rather an original character.
    <br></br>
    <b>NOTE:</b> I purposely only selected pictures from MyFigureCollection that were tagged as "Official" (official promotional photos provided by the manufacturer and reuploaded to MFC) or "Chan" (pictures from the Internet from unknown photographers/sources that were reuploaded to MFC) to feature on this page because I didn't want to use MyFigureCollection users' personal pictures of the figurines without their permission.
    <br></br>
</div>

app/views/about/index.html.erb
<h2 class="page_title">About This Website</h2>
<div id="about_container">
    <b><a href="<%= gothanimeangel_path %>">About Gothic Anime Angel<a>
    <br></br>
    <a href = "<%= peacesignmiku_path %>">About the Favicon ("Peace Sign/V Sign Miku")</a></b>
    <br></br>
    <b>What is Nightcore?</b>
    <br></br>
    Nightcore is a music movement characterized by editing music tracks to increase their pitch and speed by approximately 35%<a href="#footnote" id="footnote_link"><sup>[1]</sup></a>.
    <br></br>
    The term "nightcore" was coined by the Norwegian DJs Thomas S. Nilsen (DJ TNT) and Steffen Ojala Søderholm (DJ SOS) in 2001, who together formed the musical duo Nightcore<a href="#footnote" id="footnote_link"><sup>[1]</sup></a>. Their official website gives the following explanation for their name:<a href="#footnote" id="footnote_link"><sup>[2]</sup></a>
    <br></br><div id="quote">"Our name, 'Nightcore', means that we are the core of the night, so you'll dance all night long." - Thomas S. Nilsen & Steffen Ojala Søderholm, 2003</div>
    <br>The duo mixed pitched-up and sped-up versions of primarily trance and Eurodance songs, releasing several Nightcore albums which were distributed locally through CD. Funnily enough, despite Nightcore's modern reputation as an Internet-based music movement, Nilsen and Soderholm stated that they never uploaded any of their tracks online and have no idea how their tracks ended up on platforms such as LimeWire and YouTube<a href="#footnote" id="footnote_link"><sup>[3]</sup></a><a href="#footnote" id="footnote_link"><sup>[4]</sup></a>.
    <br></br>Around 2009, various other people eventually started to make their own Nightcore-style pitch and speed edits of popular songs and upload them to YouTube, typically accompanied by thumbnails and visuals with anime-style artwork<a href="#footnote" id="footnote_link"><sup>[1]</sup></a>, although this was not a characteristic of the music uploaded by the original Nightcore duo.<a href="#footnote" id="footnote_link"><sup>[3]</sup></a>
    <br></br>
    <b>What is the purpose of this site?</b>
    <br></br>
    As aforementioned, a quintessential aspect of Nightcore videos on YouTube is the inclusion of anime-style artwork. In fact, the artworks associated with the most popular Nightcore videos have become iconic themselves within Internet culture. However, the sources and origin of these artworks, namely for Nightcore YouTube uploads from roughly 2009-2013<a href="#footnote" id="footnote_link"><sup>[5]</sup></a>, are often unknown. Unfortunately, it was generally not customary for Nightcore creators on YouTube to credit the source and artist for the images they used in their videos in this time period. 
    <br></br>Based on my personal observations, a majority of these artworks tend to originate from Japanese eroge visual novels published in the early 2000s and were obscure outside of Japan. Most likely, the (typically not Japanese) Nightcore creators on YouTube looked for "anime art" on search engines and used whatever cool art they could find, which had most likely been indexed from non-Japanese anime image boards (i.e. <a href="https://www.zerochan.net/">Zerochan</a>) or wallpaper websites. My best guess would be that a majority of the time, these Nightcore YouTubers didn't actually have knowledge of the source or the artist of the images that they used in their videos, and thus usually did not put this information into the descriptions of their videos.
    <br></br>As of 2023, the year that I am writing this, the practice of crediting the artist has fortunately become far more recognized in Internet spaces than it was in the era of 2009-2013 Nightcore YouTube videos. Here and there, recent comments on YouTube and other online spaces have been able to identify the sources of many artworks made Internet-famous by Nightcore!
    <br></br>However, I still wish to provide a centralized space on the web for distributing information about the sources and artists of a multitude of artworks associated with popular Nightcore videos uploaded to YouTube in roughly this 2009-2013 time period. In addition, I wish to provide data on the original artists of the music tracks of which the Nightcore edit versions have become viral, as several of them were often sadly eclipsed in popularity by the Nightcore version of their songs. I will generally not be including entries from more recent Nightcore videos as modern Nightcore YouTubers are usually very adept at including this information in their video descriptions already.
    <br></br>In conclusion, my goal was to create a website that allows people to appreciate the artists who made the artworks that bring them major nostalgia through Nightcore videos from the late 2000s/early 2010s (as well as recognizing the original artists of the songs which were featured in these videos!). This online database features information such as the sources and artists of the artwork, the original artist of the song, publishing dates for both the artwork and the Nightcore video, and individually written descriptions with my personal commentary on the source, artwork, or the Nightcore video. It is for this reason that I would like to refer to this website as not only a database, but also an online art museum of sorts :)
    <br></br>I track down all of this information by myself manually, typically using tools such as <a href="https://saucenao.com/">SauceNAO</a> as well as anime image boards (i.e. <a href="https://www.zerochan.net/">Zerochan</a>, <a href="https://safebooru.donmai.us/">Danbooru</a>, <a href="https://e-shuushuu.net/">Shuushuu</a>, etc.), to ensure the accuracy of the information that I provide on this website. I hope that my efforts can help some people out there find the origins of artworks that they have admired since the dawn of the Nightcore YouTube scene.
    <br></br><br></br><div id="footnote">
    <b>References & Footnotes</b>
    <br></br><sup>1</sup> <i>Nightcore. (2023). Retrieved December 31, 2023, from <a href="https://en.wikipedia.org/wiki/Nightcore">https://en.wikipedia.org/wiki/Nightcore</a></i>
    <br></br><sup>2</sup> <i>:!: Nightcore is Hardcore :!: (2003). <a href="https://web.archive.org/web/20030827070658/http:/www2.hemsida.net/steffie/nightcore/biography.html">https://web.archive.org/web/20030827070658/http:/www2.hemsida.net/steffie/nightcore/biography.html</a></i>
    <br></br><sup>3</sup> <i>Roy. (2011). NIGHTCORE INTERVIEW | SUPERSUPER! Magazine. <a href="https://web.archive.org/web/20111106093115/http://www.thesupersuper.com/featured/nightcore-interview/">https://web.archive.org/web/20111106093115/http://www.thesupersuper.com/featured/nightcore-interview/</a></i>
    <br></br><sup>4</sup> <i>Nightcore. (2012). Biography. Welcome. <a href="https://web.archive.org/web/20131224115541/http://nightcore.net/biography/">https://web.archive.org/web/20131224115541/http://nightcore.net/biography/</a></i>
    <br></br><sup>5</sup> I do also include pitch-edited uploads of trance songs with anime-style artwork that aren't necessarily labelled as "Nightcore", many of which predate 2009. Sped-up edits of trance and Eurodance songs with anime-style visuals were popularized prior to Nightcore's breakthrough on YouTube and other online spaces, such as <a href="https://en.wikipedia.org/wiki/Caramelldansen#Background">Caramelldansen</a> in 2005.
</div>

app/views/about/peacesignmiku.html.erb
<h2 class="page_title">About "Peace Sign/V Sign Miku"</h2>
<div id="about_goth">
    <div id="about_miku"><%= image_tag('miku.png') %>
    <br></br>
    In a 2016 post, VOCALOID Amino user <a href="https://aminoapps.com/c/vocaloid/page/user/glitchloid-hiatus/xpPf_of6VzM72XvWZmGa5xNRN5aJE87uB">glitchloid</a> described the above illustration as having "haunt[ed] Vocaloid Amino" and that "for ages now, [they've] been on a quest to find its source". I think that this is an apt descriptor for the extent to which this artwork, a fanart of the VOCALOID character Hatsune Miku, has been reposted all over the Internet (not just Amino!) over the years- to the point where information on the original artist has become obscure. For this article, my goal is much the same as glitchloid's: explore the origins of this iconic fanart of Hatsune Miku that has pervaded various online spaces since at least the early 2010s.
    <br></br>
    Unlike "gothic anime angel", it is very clear that "peace sign Miku" is a fanart of Hatsune Miku. The only work left for me to do was to determine the original artist of the image. 
    <br></br>
    In <a href="https://aminoapps.com/c/vocaloid/page/blog/peace-signs-miku-the-artist-possibly-found/06aI_kuKj164NnDXPoWq62vdmkp0x2n">their Amino post</a>, titled "Peace Signs Miku: The Artist Possibly Found...?", glitchloid documented their process of using SauceNAO to conduct a reverse image search on the illustration, and stated that a <b>possible</b> result was a Pixiv user by the username "HRN" (Pixiv ID 52866039), whose account was deleted before glitchloid's post. 
    <br></br>
    First of all, I would like to commend glitchloid's work, as their post was one of the only active efforts to source the image that I could manage to find online (although likely not the first, as fellow VOCALOID Amino user Daylight stated in the comment section of glitchloid's post; "I think I sourced it months ago but I'm glad it's back"). I was unable to find Daylight's post on the subject due to Amino not allowing me to view their post history farther back than April of 2020, but I presume that they came to the same conclusion as glitchloid.
    <br></br>
    As will soon become evident, I came to a very different conclusion as to the original artist of "peace sign Miku". However, I want to take a moment to emphasize that glitchloid did indeed address in their post that SauceNAO's result for the image was only a possibility and not a guarantee, and that I intend no hostility in challenging their conclusion. I believe that "HRN" was one of many Pixiv users who re-uploaded the image to their profiles and that the constant spam of reuploads of the image bloated SauceNAO's results with unauthorized reuploads instead of the original post of the image or links to the image on image boards.
    <br></br>
    Speaking of image boards, it was through them that I was able to find out the identity of the original artist of "peace sign Miku". After cross-referencing information on the image provided on <a href="https://e-shuushuu.net/image/571575/">shuushuu</a>, <a href="https://danbooru.donmai.us/artists/77393">Danbooru</a>, and <a href="https://www.zerochan.net/Pixiv+Id+3879881">Zerochan</a>, I was able to confidently conclude that the <b><u>original artist went under the online aliases "Imouto" (いもうと。) and "takahashisan" (Pixiv ID 3879881)</u></b>.
    <br></br>
    Both Imouto's <a href="https://www.pixiv.net/en/users/3879881">Pixiv account</a> and <a href="http://twitter.com/iiimoutooo">Twitter</a> (@iiimoutooo) have been deactivated, as have their <a href="https://www.stickam.jp/profile/iiimoutooo">Stickam account</a> (unsurprisingly, since Stickam shut down in 2013) and <a href="http://imoutooo.blog.fc2.com">personal blog</a>. I was unable to find archives for any of these (nor was I able to find an archive for the <a href="https://www.pixiv.net/en/artworks/26228723">original Pixiv upload of "peace sign Miku"</a>, so I am unable to confirm the exact date it was first uploaded online, it was uploaded to Danbooru in 2013).
    <br></br>
    However, Imouto's <a href="https://com.nicovideo.jp/community/co1504396">NicoNico account</a>, where they live-streamed drawing, playing video games, and singing, remains up. In their NicoNico profile, which has not been updated since 2012, they state that they are a professional illustrator and use Photoshop CS5 and Paint Tool SAI for digital illustration work.
    <br></br>
    On their <a href="https://seiga.nicovideo.jp/user/illust/23285221">NicoNico profile</a>, Imouto posted a <a href="https://seiga.nicovideo.jp/seiga/im1824054">couple of</a> <a href="https://seiga.nicovideo.jp/seiga/im1750508">drawings of Miku</a> (although not the "peace sign Miku" illustration), as well as a <a href="https://seiga.nicovideo.jp/seiga/im1825234">drawing</a> of <a href="https://prettycure.fandom.com/wiki/Kise_Yayoi">Kise Yayoi</a> from <a href="https://en.wikipedia.org/wiki/Smile_PreCure!">Smile Pretty Cure!</a> All of these drawings date back to 2012.
    <br></br>
    <img src="https://cdn.donmai.us/sample/42/73/__hatsune_miku_vocaloid_drawn_by_imouto_takahashisan__sample-42738836ea8ee1a79b891dba7dfff5de.jpg">
    <img src="https://static.zerochan.net/Hatsune.Miku.full.1060605.jpg">
    <img id="kise" src="https://lohas.nicoseiga.jp/thumb/1825234i?" width="45%">
    <br></br>
    This sketch Imouto made of Miku was reuploaded to image boards from Pixiv as early as 2012:
    <br></br>
    <img src="https://cdn.donmai.us/original/99/fa/__hatsune_miku_vocaloid_drawn_by_imouto_takahashisan__99fa9e17059d73f64501702f4073ec62.png">
    <br></br>
    The Danbooru post for "peace sign miku" indicates that Imouto uploaded either a step-by-step process or a time-lapse video showing the drawing process of the illustration in a <a href="https://www.pixiv.net/en/artworks/26228723">separate Pixiv post</a> (which I was unable to find an archive for).
    <br></br>
    "peace sign Miku" likely gained viral status online through VOCALOID fans reposting the image without crediting Imouto, the original artist, to use on their websites, blogs, social media, forums, etc. At some point it probably became a top search result for cute artworks depicting Hatsune Miku, further causing people to grab the image straight from search engines instead of image boards or the original Pixiv upload and use it without Imouto's permission or credit. While the image boards that provide the information that "peace sign Miku" was illustrated by Imouto are all popular and often top results in search engines such as Google, the substantial presence of uncredited reposts of the image on social media platforms tragically likely drowned out these image boards in search results.
    </div>
</div>

app/views/articles/index.html.erb
<h2 class="page_title">Articles</h2>
<p id="disclaimer"><b>DISCLAIMER:</b> While I do not host any explicit content on this website, some artworks originate from NSFW sources. Such sources are marked as "R-18" in the "Source Type" field in their database entries. Please use discretion when looking up these sources online!</p>
<div id="search-menu">
    <%= search_form_for @q do |f| %>
        <%= f.search_field :title_cont %>
        <%= f.submit %>
    <% end %><%= select_tag :per_page, options_for_select([2,3,5,15], params[:per_page].to_i), :onchange => "if(this.value){window.location='?per_page='+this.value;}" %> entries per page
    <br>
    <form>
    Sort by:
        <select name = "sort_by">
            <option value = "id">Select</option>
            <option value = "id">--------</option>
            <option value = "title">Title</option>
            <option value = "uploadDate">Upload Date</option>
            <option value = "id">ID</option>
        </select>
        <select name = "sort_order">
            <option value = "ASC">Asc/Desc</option>
            <option value = "ASC">--------</option>
            <option value = "ASC">Ascending</option>
            <option value = "DESC">Descending</option>
        </select>
        <input type="submit" value="Sort"/>
    </form>
</div>

<% if false %>
<%= select_tag :sort_by, options_for_select(["title", "uploadDate", "id"], params[:sort_by]), :onchange => "if(this.value){window.location='?sort_by='+this.value;}" %>
<%= select_tag :sort_order, options_for_select(["ASC", "DESC"], params[:sort_order]), :onchange => "if(this.value){window.location='?sort_order='+this.value;}" %>
<% end %>


<div id="main_table">
    <table>
        <tr>
            <td><b>Song Title</b></td>
            <td><b>Thumbnail</b></td>
            <td><b>Upload Date of Nightcore Version</b></td>
        </tr>
        <% @articles.each do |article| %>
            <tr>
                <td><%= link_to article.title, article %></td>
                <td><div id="thumbnail"><%= link_to image_tag(article.imgPath), article %></div></td>
                <td><%= article.uploadDate %></td>
            </tr>
        <% end %>
    </table>
</div>
<div id="paginate">
    <%= will_paginate @articles %>
    <%= page_entries_info @articles %>
</div>

app/views/articles/show.html.erb
<div id="back"><%= link_to "Back", :back %></div>
<h2 class="page_title"><%= @article.title %></h2>
<div id="img-container"><%= image_tag(@article.imgPath) %></div>
<table>
    <tr>
        <td><b>Source</b></td>
        <td><%= @article.source %></td>
    </tr>
    <tr>
        <td><b>Date Published</b></td>
        <td><%= @article.datePublished %></td>
    </tr>
    <tr>
        <td><b>Character(s)</b></td>
        <td><%= @article.character %></td>
    </tr>
    <tr>
        <td><b>Artist(s)</b></td>
        <td><%= @article.artist %></td>
    </tr>
    <tr>
        <td><b>Artist Links</b></td>
        <td>
            <ul>
                <%= sanitize @article.artistLinks %>
            </ul>
        </td>
    </tr>
    <tr>
        <td><b>Source Type</b></td>
        <td><%= @article.sourceType %></td>
    </tr>
    <tr>
        <td><b>Associated Nightcore Video</b></td>
        <td>
            <table>
                <tr>
                    <td><b>Song Title</b></td>
                    <td><%= @article.songTitle %></td>
                </tr>
                <tr>
                    <td><b>Artist</b></td>
                    <td><%= @article.songArtist %></td>
                </tr>
                <tr>
                    <td><b>Uploader</b></td>
                    <td><%= @article.uploader %></td>
                </tr>
                <tr>
                    <td><b>Platform</b></td>
                    <td><%= @article.platform %></td>
                </tr>
                <tr>
                    <td><b>Upload Date</b></td>
                    <td><%= @article.uploadDate %></td>
                </tr>
                <tr>
                    <td><b>Link</b></td>
                    <td><iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @article.video %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td><b>Description</b></td>
        <td><%= sanitize @article.description %></td>
    </tr>
    <tr>
        <td><b>Links</b></td>
        <td>
            <ul>
                <%= sanitize @article.links %>
            </ul>
        </td>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nightcore Art Museum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('miku.png') %>
    <div id="header">
      <div id="menu">
      <div id="logo"><%= image_tag('logo_gif.gif') %></div>
      <h2 style="display:inline;"><%= link_to "Home", articles_path %></h2>
      <h2 style="display:inline;"><%= link_to "About", about_path %></h2>
      <h2 style="display:inline;"><a href="https://github.com/corroscience/Nightcore-Art-Database">GitHub</a></h2>
      </div>
    </div>
  </head>

  <body>
    <%= yield %>
    <p id="footer">Since 2023, website made by <a href="https://github.com/corroscience">corroscience</a> <3</p>
  </body>
</html>